In [1]:
import sys
from pathlib import Path

ROOT = Path().resolve().parents[1] # go up n levels (adjust as needed)
sys.path.append(str(ROOT))

from config import PROJECT_ROOT, APT_ROOT
from apt_project import *

In [2]:
import json
import pandas as pd
from pprint import pprint
import matplotlib.pyplot as plt
import networkx as nx
import seaborn as sns
import numpy as np

Creating group_techniques df for previous time periods

In [3]:
import json 
import pandas as pd
def create_df(file_name):
    with open(file_name, "r", encoding="utf-8") as f:
        stix = json.load(f)
    objects = stix.get("objects", [])
    group_objs = [o for o in objects if o.get("type") == "intrusion-set"]
    rel_objs = [o for o in objects if o.get("type") == "relationship"]
    tech_objs = [o for o in objects if o.get("type") == "attack-pattern"]

    def technique_row(o):
        # external id e.g. T1003 usually in external_references where source_name == 'mitre-attack'
        ext_refs = o.get("external_references", [])
        mitre_ref = next((r for r in ext_refs if r.get("source_name") == "mitre-attack"), {})
        external_id = mitre_ref.get("external_id")
        # kill_chain_phases may contain tactic phase names
        kcp = o.get("kill_chain_phases") or o.get("kill_chain_phases", []) or []
        phases = [p.get("phase_name") for p in kcp if isinstance(p, dict) and p.get("phase_name")]
        platforms = o.get("x_mitre_platforms") or o.get("x-mitre-platforms") or []
        data_sources = o.get("x_mitre_data_sources") or []
        return {
            "id": o.get("id"),
            "tech_name": o.get("name"),
            "external_id": external_id,
            "description": o.get("description"),
            "platforms": platforms,
            "kill_chain_phases": phases,
            "raw": o
        }

    tech_df = pd.DataFrame([technique_row(o) for o in tech_objs])
    # Filter relevant "uses" relationships
    uses_rels = [
        r for r in rel_objs
        if r.get("relationship_type") == "uses"
        and r.get("source_ref", "").startswith("intrusion-set--")
        and r.get("target_ref", "").startswith("attack-pattern--")
    ]

    rows = []
    for r in uses_rels:
        group_id = r["source_ref"]
        tech_id = r["target_ref"]

        # Lookup group name
        group_name = next((g["name"] for g in group_objs if g["id"] == group_id), None)

        # Lookup technique information
        tech = next((t for t in tech_df.to_dict("records") if t["id"] == tech_id), None)

        rows.append({
            "group_id": group_id,
            "group_name": group_name,
            "technique_id": tech_id,
            "technique_name": tech.get("tech_name") if tech else None,
            "tactic": tech.get("kill_chain_phases") if tech else None,
            "technique_description": tech.get("description") if tech else None,
            "relationship_description": r.get("description"),
        })
    ret = pd.DataFrame(rows)
    time_period = stix.get("objects")[0].get("modified")
    return time_period, ret

In [4]:
dfs = dict() 
# group_techniques_df is already the latest time period
dfs[1] = group_techniques_df # "2025-11-13T14:00:00.188Z"
# 1 time period back
time_period, df = create_df("../../enterprise-attack/enterprise-attack-17.1.json")
print(f"time period 2 is {time_period} ")
dfs[2] = df
# 2 time periods back
time_period, df = create_df("../../enterprise-attack/enterprise-attack-16.1.json")
print(f"time period 3 is {time_period} ")
dfs[3] = df
time_period, df = create_df("../../enterprise-attack/enterprise-attack-15.1.json")
print(f"time period 4 is {time_period} ")
dfs[4] = df
time_period, df = create_df("../../enterprise-attack/enterprise-attack-14.1.json")
print(f"time period 5 is {time_period} ")
dfs[5] = df
time_period, df = create_df("../../enterprise-attack/enterprise-attack-13.1.json")
print(f"time period 6 is {time_period} ")
dfs[6] = df
time_period, df = create_df("../../enterprise-attack/enterprise-attack-12.1.json")
print(f"time period 7 is {time_period} ")
dfs[7] = df

time period 2 is 2025-05-06T14:00:00.188Z
time period 3 is 2024-11-12T14:00:00.188Z
time period 4 is 2024-05-02T14:00:00.188Z
time period 5 is 2023-11-14T14:00:00.188Z
time period 6 is 2023-05-09T14:00:00.188Z
time period 7 is 2022-11-08T14:00:00.188Z

In [5]:
for time_period, df in dfs.items():
    print(f"Time Period: {time_period}, Number of Records: {len(df)}")
    display(df.head(10))

Time Period: 1, Number of Records: 4362

,group_id,group_name,technique_id,technique_name,tactic,technique_description,relationship_description
0,intrusion-set--01e28736-2ffc-455b-9880-ed4d140...,Indrik Spider,attack-pattern--65f2d882-3f41-4d48-8a06-29af77...,LSASS Memory,[credential-access],Adversaries may attempt to access credential m...,[Indrik Spider](https://attack.mitre.org/group...
1,intrusion-set--b7f627e2-0817-4cd5-8d50-e75f8aa...,LuminousMoth,attack-pattern--10ffac09-e42d-4f56-ab20-db94c6...,Steal Web Session Cookie,[credential-access],An adversary may steal web application or serv...,[LuminousMoth](https://attack.mitre.org/groups...
2,intrusion-set--918da025-04bd-48af-b6c4-f3e4d1b...,Medusa Group,attack-pattern--f5d8eed6-48a9-4cdf-a3d7-d1ffa9...,Inhibit System Recovery,[impact],Adversaries may delete or remove built-in data...,[Medusa Group](https://attack.mitre.org/groups...
3,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--635cbe30-392d-4e27-978e-667743...,Local Account,[persistence],Adversaries may create a local account to main...,[Wizard Spider](https://attack.mitre.org/group...
4,intrusion-set--3753cc21-2dae-4dfb-8481-d004e74...,FIN7,attack-pattern--ef67e13e-5598-4adc-bdb2-998225...,Malicious Link,[execution],An adversary may rely upon a user clicking a m...,[FIN7](https://attack.mitre.org/groups/G0046) ...
5,intrusion-set--461b8e25-8f4a-4ea2-a4a8-e39df7c...,UNC3886,attack-pattern--b0533c6e-8fea-4788-874f-b799ca...,Indicator Removal from Tools,[defense-evasion],Adversaries may remove indicators from tools i...,[UNC3886](https://attack.mitre.org/groups/G104...
6,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--970a3432-3237-47ad-bcca-7d8cbb...,PowerShell,[execution],Adversaries may abuse PowerShell commands and ...,[WIRTE](https://attack.mitre.org/groups/G0090)...
7,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--b18eae87-b469-4e14-b454-b171b4...,Non-Standard Port,[command-and-control],Adversaries may communicate using a protocol a...,[WIRTE](https://attack.mitre.org/groups/G0090)...
8,intrusion-set--461b8e25-8f4a-4ea2-a4a8-e39df7c...,UNC3886,attack-pattern--63b24abc-5702-4745-b1e4-ac70b2...,Search Threat Vendor Data,[reconnaissance],Threat actors may seek information/indicators ...,[UNC3886](https://attack.mitre.org/groups/G104...
9,intrusion-set--1c63d4ec-0a75-4daa-b1df-0d11af3...,Dragonfly,attack-pattern--53ac20cd-aca3-406e-9aa0-9fc7fd...,Archive Collected Data,[collection],An adversary may compress and/or encrypt data ...,[Dragonfly](https://attack.mitre.org/groups/G0...

Time Period: 2, Number of Records: 4046

,group_id,group_name,technique_id,technique_name,tactic,technique_description,relationship_description
0,intrusion-set--01e28736-2ffc-455b-9880-ed4d140...,Indrik Spider,attack-pattern--65f2d882-3f41-4d48-8a06-29af77...,LSASS Memory,[credential-access],Adversaries may attempt to access credential m...,[Indrik Spider](https://attack.mitre.org/group...
1,intrusion-set--b7f627e2-0817-4cd5-8d50-e75f8aa...,LuminousMoth,attack-pattern--10ffac09-e42d-4f56-ab20-db94c6...,Steal Web Session Cookie,[credential-access],An adversary may steal web application or serv...,[LuminousMoth](https://attack.mitre.org/groups...
2,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--635cbe30-392d-4e27-978e-667743...,Local Account,[persistence],Adversaries may create a local account to main...,[Wizard Spider](https://attack.mitre.org/group...
3,intrusion-set--3753cc21-2dae-4dfb-8481-d004e74...,FIN7,attack-pattern--ef67e13e-5598-4adc-bdb2-998225...,Malicious Link,[execution],An adversary may rely upon a user clicking a m...,[FIN7](https://attack.mitre.org/groups/G0046) ...
4,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--970a3432-3237-47ad-bcca-7d8cbb...,PowerShell,[execution],Adversaries may abuse PowerShell commands and ...,[WIRTE](https://attack.mitre.org/groups/G0090)...
5,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--b18eae87-b469-4e14-b454-b171b4...,Non-Standard Port,[command-and-control],Adversaries may communicate using a protocol a...,[WIRTE](https://attack.mitre.org/groups/G0090)...
6,intrusion-set--1c63d4ec-0a75-4daa-b1df-0d11af3...,Dragonfly,attack-pattern--53ac20cd-aca3-406e-9aa0-9fc7fd...,Archive Collected Data,[collection],An adversary may compress and/or encrypt data ...,[Dragonfly](https://attack.mitre.org/groups/G0...
7,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--e7cbc1de-1f79-48ee-abfd-da1241...,Code Signing Certificates,[resource-development],Adversaries may buy and/or steal code signing ...,[Wizard Spider](https://attack.mitre.org/group...
8,intrusion-set--96e239be-ad99-49eb-b127-3007b8c...,Equation,attack-pattern--dfebc3b7-d19d-450b-81c7-6dafe4...,Hidden File System,[defense-evasion],Adversaries may use a hidden file system to co...,[Equation](https://attack.mitre.org/groups/G00...
9,intrusion-set--4ca1929c-7d64-4aab-b849-badbfc0...,OilRig,attack-pattern--e7cbc1de-1f79-48ee-abfd-da1241...,Code Signing Certificates,[resource-development],Adversaries may buy and/or steal code signing ...,[OilRig](https://attack.mitre.org/groups/G0049...

Time Period: 3, Number of Records: 4323

,group_id,group_name,technique_id,technique_name,tactic,technique_description,relationship_description
0,intrusion-set--01e28736-2ffc-455b-9880-ed4d140...,Indrik Spider,attack-pattern--65f2d882-3f41-4d48-8a06-29af77...,LSASS Memory,[credential-access],Adversaries may attempt to access credential m...,[Indrik Spider](https://attack.mitre.org/group...
1,intrusion-set--b7f627e2-0817-4cd5-8d50-e75f8aa...,LuminousMoth,attack-pattern--10ffac09-e42d-4f56-ab20-db94c6...,Steal Web Session Cookie,[credential-access],An adversary may steal web application or serv...,[LuminousMoth](https://attack.mitre.org/groups...
2,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--635cbe30-392d-4e27-978e-667743...,Local Account,[persistence],Adversaries may create a local account to main...,[Wizard Spider](https://attack.mitre.org/group...
3,intrusion-set--3753cc21-2dae-4dfb-8481-d004e74...,FIN7,attack-pattern--ef67e13e-5598-4adc-bdb2-998225...,Malicious Link,[execution],An adversary may rely upon a user clicking a m...,[FIN7](https://attack.mitre.org/groups/G0046) ...
4,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--970a3432-3237-47ad-bcca-7d8cbb...,PowerShell,[execution],Adversaries may abuse PowerShell commands and ...,[WIRTE](https://attack.mitre.org/groups/G0090)...
5,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--b18eae87-b469-4e14-b454-b171b4...,Non-Standard Port,[command-and-control],Adversaries may communicate using a protocol a...,[WIRTE](https://attack.mitre.org/groups/G0090)...
6,intrusion-set--1c63d4ec-0a75-4daa-b1df-0d11af3...,Dragonfly,attack-pattern--53ac20cd-aca3-406e-9aa0-9fc7fd...,Archive Collected Data,[collection],An adversary may compress and/or encrypt data ...,[Dragonfly](https://attack.mitre.org/groups/G0...
7,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--e7cbc1de-1f79-48ee-abfd-da1241...,Code Signing Certificates,[resource-development],Adversaries may buy and/or steal code signing ...,[Wizard Spider](https://attack.mitre.org/group...
8,intrusion-set--96e239be-ad99-49eb-b127-3007b8c...,Equation,attack-pattern--dfebc3b7-d19d-450b-81c7-6dafe4...,Hidden File System,[defense-evasion],Adversaries may use a hidden file system to co...,[Equation](https://attack.mitre.org/groups/G00...
9,intrusion-set--c21dd6f1-1364-4a70-a1f7-783080e...,Fox Kitten,attack-pattern--e6919abc-99f9-4c6c-95a5-14761e...,Ingress Tool Transfer,[command-and-control],Adversaries may transfer tools or other files ...,[Fox Kitten](https://attack.mitre.org/groups/G...

Time Period: 4, Number of Records: 3918

,group_id,group_name,technique_id,technique_name,tactic,technique_description,relationship_description
0,intrusion-set--01e28736-2ffc-455b-9880-ed4d140...,Indrik Spider,attack-pattern--65f2d882-3f41-4d48-8a06-29af77...,LSASS Memory,[credential-access],Adversaries may attempt to access credential m...,[Indrik Spider](https://attack.mitre.org/group...
1,intrusion-set--b7f627e2-0817-4cd5-8d50-e75f8aa...,LuminousMoth,attack-pattern--10ffac09-e42d-4f56-ab20-db94c6...,Steal Web Session Cookie,[credential-access],An adversary may steal web application or serv...,[LuminousMoth](https://attack.mitre.org/groups...
2,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--635cbe30-392d-4e27-978e-667743...,Local Account,[persistence],Adversaries may create a local account to main...,[Wizard Spider](https://attack.mitre.org/group...
3,intrusion-set--3753cc21-2dae-4dfb-8481-d004e74...,FIN7,attack-pattern--ef67e13e-5598-4adc-bdb2-998225...,Malicious Link,[execution],An adversary may rely upon a user clicking a m...,[FIN7](https://attack.mitre.org/groups/G0046) ...
4,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--970a3432-3237-47ad-bcca-7d8cbb...,PowerShell,[execution],Adversaries may abuse PowerShell commands and ...,[WIRTE](https://attack.mitre.org/groups/G0090)...
5,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--b18eae87-b469-4e14-b454-b171b4...,Non-Standard Port,[command-and-control],Adversaries may communicate using a protocol a...,[WIRTE](https://attack.mitre.org/groups/G0090)...
6,intrusion-set--1c63d4ec-0a75-4daa-b1df-0d11af3...,Dragonfly,attack-pattern--53ac20cd-aca3-406e-9aa0-9fc7fd...,Archive Collected Data,[collection],An adversary may compress and/or encrypt data ...,[Dragonfly](https://attack.mitre.org/groups/G0...
7,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--e7cbc1de-1f79-48ee-abfd-da1241...,Code Signing Certificates,[resource-development],Adversaries may buy and/or steal code signing ...,[Wizard Spider](https://attack.mitre.org/group...
8,intrusion-set--96e239be-ad99-49eb-b127-3007b8c...,Equation,attack-pattern--dfebc3b7-d19d-450b-81c7-6dafe4...,Hidden File System,[defense-evasion],Adversaries may use a hidden file system to co...,[Equation](https://attack.mitre.org/groups/G00...
9,intrusion-set--c21dd6f1-1364-4a70-a1f7-783080e...,Fox Kitten,attack-pattern--e6919abc-99f9-4c6c-95a5-14761e...,Ingress Tool Transfer,[command-and-control],Adversaries may transfer tools or other files ...,[Fox Kitten](https://attack.mitre.org/groups/G...

Time Period: 5, Number of Records: 3743

,group_id,group_name,technique_id,technique_name,tactic,technique_description,relationship_description
0,intrusion-set--01e28736-2ffc-455b-9880-ed4d140...,Indrik Spider,attack-pattern--65f2d882-3f41-4d48-8a06-29af77...,LSASS Memory,[credential-access],Adversaries may attempt to access credential m...,[Indrik Spider](https://attack.mitre.org/group...
1,intrusion-set--b7f627e2-0817-4cd5-8d50-e75f8aa...,LuminousMoth,attack-pattern--10ffac09-e42d-4f56-ab20-db94c6...,Steal Web Session Cookie,[credential-access],An adversary may steal web application or serv...,[LuminousMoth](https://attack.mitre.org/groups...
2,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--635cbe30-392d-4e27-978e-667743...,Local Account,[persistence],Adversaries may create a local account to main...,[Wizard Spider](https://attack.mitre.org/group...
3,intrusion-set--3753cc21-2dae-4dfb-8481-d004e74...,FIN7,attack-pattern--ef67e13e-5598-4adc-bdb2-998225...,Malicious Link,[execution],An adversary may rely upon a user clicking a m...,[FIN7](https://attack.mitre.org/groups/G0046) ...
4,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--970a3432-3237-47ad-bcca-7d8cbb...,PowerShell,[execution],Adversaries may abuse PowerShell commands and ...,[WIRTE](https://attack.mitre.org/groups/G0090)...
5,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--b18eae87-b469-4e14-b454-b171b4...,Non-Standard Port,[command-and-control],Adversaries may communicate using a protocol a...,[WIRTE](https://attack.mitre.org/groups/G0090)...
6,intrusion-set--1c63d4ec-0a75-4daa-b1df-0d11af3...,Dragonfly,attack-pattern--53ac20cd-aca3-406e-9aa0-9fc7fd...,Archive Collected Data,[collection],An adversary may compress and/or encrypt data ...,[Dragonfly](https://attack.mitre.org/groups/G0...
7,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--e7cbc1de-1f79-48ee-abfd-da1241...,Code Signing Certificates,[resource-development],Adversaries may buy and/or steal code signing ...,[Wizard Spider](https://attack.mitre.org/group...
8,intrusion-set--96e239be-ad99-49eb-b127-3007b8c...,Equation,attack-pattern--dfebc3b7-d19d-450b-81c7-6dafe4...,Hidden File System,[defense-evasion],Adversaries may use a hidden file system to co...,[Equation](https://attack.mitre.org/groups/G00...
9,intrusion-set--c21dd6f1-1364-4a70-a1f7-783080e...,Fox Kitten,attack-pattern--e6919abc-99f9-4c6c-95a5-14761e...,Ingress Tool Transfer,[command-and-control],Adversaries may transfer tools or other files ...,[Fox Kitten](https://attack.mitre.org/groups/G...

Time Period: 6, Number of Records: 3562

,group_id,group_name,technique_id,technique_name,tactic,technique_description,relationship_description
0,intrusion-set--01e28736-2ffc-455b-9880-ed4d140...,Indrik Spider,attack-pattern--65f2d882-3f41-4d48-8a06-29af77...,LSASS Memory,[credential-access],Adversaries may attempt to access credential m...,[Indrik Spider](https://attack.mitre.org/group...
1,intrusion-set--b7f627e2-0817-4cd5-8d50-e75f8aa...,LuminousMoth,attack-pattern--10ffac09-e42d-4f56-ab20-db94c6...,Steal Web Session Cookie,[credential-access],An adversary may steal web application or serv...,[LuminousMoth](https://attack.mitre.org/groups...
2,intrusion-set--3753cc21-2dae-4dfb-8481-d004e74...,FIN7,attack-pattern--ef67e13e-5598-4adc-bdb2-998225...,Malicious Link,[execution],An adversary may rely upon a user clicking a m...,[FIN7](https://attack.mitre.org/groups/G0046) ...
3,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--970a3432-3237-47ad-bcca-7d8cbb...,PowerShell,[execution],Adversaries may abuse PowerShell commands and ...,[WIRTE](https://attack.mitre.org/groups/G0090)...
4,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--b18eae87-b469-4e14-b454-b171b4...,Non-Standard Port,[command-and-control],Adversaries may communicate using a protocol a...,[WIRTE](https://attack.mitre.org/groups/G0090)...
5,intrusion-set--1c63d4ec-0a75-4daa-b1df-0d11af3...,Dragonfly,attack-pattern--53ac20cd-aca3-406e-9aa0-9fc7fd...,Archive Collected Data,[collection],An adversary may compress and/or encrypt data ...,[Dragonfly](https://attack.mitre.org/groups/G0...
6,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--e7cbc1de-1f79-48ee-abfd-da1241...,Code Signing Certificates,[resource-development],Adversaries may buy and/or steal code signing ...,[Wizard Spider](https://attack.mitre.org/group...
7,intrusion-set--96e239be-ad99-49eb-b127-3007b8c...,Equation,attack-pattern--dfebc3b7-d19d-450b-81c7-6dafe4...,Hidden File System,[defense-evasion],Adversaries may use a hidden file system to co...,[Equation](https://attack.mitre.org/groups/G00...
8,intrusion-set--c21dd6f1-1364-4a70-a1f7-783080e...,Fox Kitten,attack-pattern--e6919abc-99f9-4c6c-95a5-14761e...,Ingress Tool Transfer,[command-and-control],Adversaries may transfer tools or other files ...,[Fox Kitten](https://attack.mitre.org/groups/G...
9,intrusion-set--c21dd6f1-1364-4a70-a1f7-783080e...,Fox Kitten,attack-pattern--7385dfaf-6886-4229-9ecd-6fd678...,Command and Scripting Interpreter,[execution],Adversaries may abuse command and script inter...,[Fox Kitten](https://attack.mitre.org/groups/G...

Time Period: 7, Number of Records: 3459

,group_id,group_name,technique_id,technique_name,tactic,technique_description,relationship_description
0,intrusion-set--01e28736-2ffc-455b-9880-ed4d140...,Indrik Spider,attack-pattern--65f2d882-3f41-4d48-8a06-29af77...,LSASS Memory,[credential-access],Adversaries may attempt to access credential m...,[Indrik Spider](https://attack.mitre.org/group...
1,intrusion-set--3753cc21-2dae-4dfb-8481-d004e74...,FIN7,attack-pattern--ef67e13e-5598-4adc-bdb2-998225...,Malicious Link,[execution],An adversary may rely upon a user clicking a m...,[FIN7](https://attack.mitre.org/groups/G0046) ...
2,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--970a3432-3237-47ad-bcca-7d8cbb...,PowerShell,[execution],Adversaries may abuse PowerShell commands and ...,[WIRTE](https://attack.mitre.org/groups/G0090)...
3,intrusion-set--f8cb7b36-62ef-4488-8a6d-a7033e3...,WIRTE,attack-pattern--b18eae87-b469-4e14-b454-b171b4...,Non-Standard Port,[command-and-control],Adversaries may communicate using a protocol a...,[WIRTE](https://attack.mitre.org/groups/G0090)...
4,intrusion-set--1c63d4ec-0a75-4daa-b1df-0d11af3...,Dragonfly,attack-pattern--53ac20cd-aca3-406e-9aa0-9fc7fd...,Archive Collected Data,[collection],An adversary may compress and/or encrypt data ...,[Dragonfly](https://attack.mitre.org/groups/G0...
5,intrusion-set--dd2d9ca6-505b-4860-a604-233685b...,Wizard Spider,attack-pattern--e7cbc1de-1f79-48ee-abfd-da1241...,Code Signing Certificates,[resource-development],Adversaries may buy and/or steal code signing ...,[Wizard Spider](https://attack.mitre.org/group...
6,intrusion-set--96e239be-ad99-49eb-b127-3007b8c...,Equation,attack-pattern--dfebc3b7-d19d-450b-81c7-6dafe4...,Hidden File System,[defense-evasion],Adversaries may use a hidden file system to co...,[Equation](https://attack.mitre.org/groups/G00...
7,intrusion-set--c21dd6f1-1364-4a70-a1f7-783080e...,Fox Kitten,attack-pattern--e6919abc-99f9-4c6c-95a5-14761e...,Ingress Tool Transfer,[command-and-control],Adversaries may transfer tools or other files ...,[Fox Kitten](https://attack.mitre.org/groups/G...
8,intrusion-set--c21dd6f1-1364-4a70-a1f7-783080e...,Fox Kitten,attack-pattern--7385dfaf-6886-4229-9ecd-6fd678...,Command and Scripting Interpreter,[execution],Adversaries may abuse command and script inter...,[Fox Kitten](https://attack.mitre.org/groups/G...
9,intrusion-set--64b52e7d-b2c4-4a02-9372-08a463f...,Aquatic Panda,attack-pattern--b3d682b6-98f2-4fb0-aa3b-b4df00...,Obfuscated Files or Information,[defense-evasion],Adversaries may attempt to make an executable ...,[Aquatic Panda](https://attack.mitre.org/group...

In [6]:
import pandas as pd

# Given: dfs = {1: df1, 2: df2, 3: df3} where keys are time periods (1=newest, 3=oldest)

# ------------------------------------------------------------
# STEP 1: Compute usage per technique per period
# ------------------------------------------------------------
usage_frames = []

for period, df in dfs.items():
    total_groups = df["group_name"].nunique()
    
    usage = (
        df.groupby("technique_name")["group_name"]
        .nunique()
        .reset_index(name="num_groups_using")
    )
    
    usage["usage"] = usage["num_groups_using"] / total_groups
    usage["time_period"] = period
    
    usage_frames.append(usage[["technique_name", "time_period", "usage"]])

usage_df = pd.concat(usage_frames, ignore_index=True)

# ------------------------------------------------------------
# STEP 2: Pivot to wide format
# ------------------------------------------------------------
usage_wide = usage_df.pivot(
    index="technique_name",
    columns="time_period", 
    values="usage"
)

# Rename columns to be descriptive
# period 1 = current, period 2 = t-1, period 3 = t-2
column_mapping = {
    1: "usage_current",
    2: "usage_t_minus_1",
    3: "usage_t_minus_2",
    4: "usage_t_minus_3",
    5: "usage_t_minus_4",
    6: "usage_t_minus_5",
    7: "usage_t_minus_6",
}
usage_wide.columns = [column_mapping[col] for col in usage_wide.columns]

# Reset index to make technique_name a column
usage_wide = usage_wide.reset_index()

# Fill NaN with 0 (technique didn't exist in that period)
usage_wide = usage_wide.fillna(0)

# Result is now a dataframe
df = usage_wide
df.head(50)

,technique_name,usage_current,usage_t_minus_1,usage_t_minus_2,usage_t_minus_3,usage_t_minus_4,usage_t_minus_5,usage_t_minus_6
0,ARP Cache Poisoning,0.011905,0.012346,0.011905,0.012739,0.013245,0.013699,0.006993
1,Abuse Elevation Control Mechanism,0.005952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Access Token Manipulation,0.017857,0.018519,0.011905,0.012739,0.013245,0.013699,0.013986
3,Accessibility Features,0.035714,0.037037,0.035714,0.038217,0.039735,0.041096,0.041958
4,Account Access Removal,0.011905,0.012346,0.011905,0.012739,0.006623,0.006849,0.006993
5,Account Discovery,0.017857,0.012346,0.029762,0.025478,0.026490,0.020548,0.020979
6,Account Manipulation,0.017857,0.012346,0.029762,0.070064,0.066225,0.061644,0.048951
7,Acquire Access,0.005952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,Acquire Infrastructure,0.047619,0.043210,0.035714,0.006369,0.000000,0.000000,0.000000
9,Add-ins,0.005952,0.006173,0.005952,0.006369,0.006623,0.006849,0.006993
10,Additional Cloud Credentials,0.005952,0.000000,0.011905,0.012739,0.013245,0.013699,0.013986
11,Additional Cloud Roles,0.017857,0.012346,0.017857,0.019108,0.013245,0.013699,0.013986
12,Additional Email Delegate Permissions,0.017857,0.018519,0.023810,0.025478,0.026490,0.027397,0.027972
13,Additional Local or Domain Groups,0.041667,0.043210,0.041667,0.000000,0.000000,0.000000,0.000000
14,Adversary-in-the-Middle,0.017857,0.012346,0.005952,0.006369,0.006623,0.006849,0.006993
15,AppCert DLLs,0.000000,0.000000,0.005952,0.006369,0.006623,0.006849,0.006993
16,AppInit DLLs,0.005952,0.006173,0.005952,0.006369,0.006623,0.006849,0.006993
17,Application Access Token,0.011905,0.012346,0.011905,0.012739,0.013245,0.013699,0.013986
18,Application Layer Protocol,0.029762,0.030864,0.035714,0.031847,0.033113,0.041096,0.041958
19,Application Shimming,0.005952,0.006173,0.005952,0.006369,0.006623,0.006849,0.006993
20,Application Window Discovery,0.017857,0.018519,0.017857,0.012739,0.013245,0.013699,0.013986
21,Archive Collected Data,0.077381,0.080247,0.083333,0.082803,0.086093,0.089041,0.083916
22,Archive via Custom Method,0.041667,0.037037,0.029762,0.031847,0.033113,0.034247,0.034965
23,Archive via Library,0.011905,0.012346,0.011905,0.012739,0.013245,0.013699,0.013986
24,Archive via Utility,0.220238,0.222222,0.220238,0.210191,0.198675,0.184932,0.188811
25,Artificial Intelligence,0.005952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,Asymmetric Cryptography,0.065476,0.061728,0.047619,0.044586,0.046358,0.041096,0.041958
27,Asynchronous Procedure Call,0.005952,0.006173,0.005952,0.006369,0.006623,0.006849,0.006993
28,At,0.017857,0.018519,0.017857,0.019108,0.019868,0.020548,0.020979
29,Audio Capture,0.005952,0.006173,0.005952,0.006369,0.006623,0.006849,0.006993
30,AutoHotKey & AutoIT,0.005952,0.006173,0.005952,0.006369,0.000000,0.000000,0.000000
31,Automated Collection,0.119048,0.123457,0.125000,0.108280,0.112583,0.116438,0.118881
32,Automated Exfiltration,0.035714,0.037037,0.047619,0.038217,0.039735,0.041096,0.041958
33,BITS Jobs,0.029762,0.030864,0.035714,0.038217,0.039735,0.034247,0.034965
34,Backup Software Discovery,0.005952,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,Bidirectional Communication,0.095238,0.092593,0.095238,0.101911,0.105960,0.109589,0.111888
36,Binary Padding,0.047619,0.043210,0.065476,0.070064,0.072848,0.068493,0.069930
37,Boot or Logon Autostart Execution,0.005952,0.006173,0.000000,0.000000,0.000000,0.000000,0.000000
38,Boot or Logon Initialization Scripts,0.023810,0.018519,0.017857,0.012739,0.013245,0.006849,0.006993
39,Bootkit,0.017857,0.018519,0.017857,0.019108,0.019868,0.020548,0.020979
40,Botnet,0.035714,0.037037,0.017857,0.012739,0.019868,0.013699,0.013986
41,Browser Bookmark Discovery,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020979
42,Browser Extensions,0.005952,0.006173,0.011905,0.012739,0.013245,0.013699,0.013986
43,Browser Information Discovery,0.035714,0.037037,0.035714,0.025478,0.019868,0.020548,0.000000
44,Browser Session Hijacking,0.005952,0.006173,0.000000,0.000000,0.000000,0.000000,0.000000
45,Brute Force,0.083333,0.080247,0.089286,0.076433,0.079470,0.082192,0.083916
46,Business Relationships,0.017857,0.018519,0.017857,0.019108,0.019868,0.020548,0.020979
47,Bypass User Account Control,0.065476,0.061728,0.059524,0.063694,0.066225,0.068493,0.069930
48,CMSTP,0.011905,0.012346,0.011905,0.012739,0.013245,0.013699,0.013986
49,COR_PROFILER,0.005952,0.006173,0.005952,0.006369,0.006623,0.006849,0.006993

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Use all lag features:
lag_columns = [col for col in usage_wide.columns if col.startswith("usage_t_minus_")]
X = usage_wide[lag_columns]

# Target stays the same
y = usage_wide["usage_current"]

# Split into train and test sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Training set size: {len(X_train)}")
print(f"Test set size: {len(X_test)}")

# ------------------------------------------------------------
# STEP 2: Train multiple models
# ------------------------------------------------------------
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha=1.0),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(n_estimators=100, random_state=42)
}

results = []

for name, model in models.items():
    print(f"\n{'='*60}")
    print(f"Training {name}...")
    print(f"{'='*60}")
    
    # Train
    model.fit(X_train, y_train)
    
    # Predict
    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)
    
    # Evaluate
    train_rmse = np.sqrt(mean_squared_error(y_train, y_pred_train))
    test_rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))
    train_mae = mean_absolute_error(y_train, y_pred_train)
    test_mae = mean_absolute_error(y_test, y_pred_test)
    train_r2 = r2_score(y_train, y_pred_train)
    test_r2 = r2_score(y_test, y_pred_test)
    
    print(f"Train RMSE: {train_rmse:.4f} | Test RMSE: {test_rmse:.4f}")
    print(f"Train MAE:  {train_mae:.4f} | Test MAE:  {test_mae:.4f}")
    print(f"Train R²:   {train_r2:.4f} | Test R²:   {test_r2:.4f}")
    
    results.append({
        "Model": name,
        "Train RMSE": train_rmse,
        "Test RMSE": test_rmse,
        "Train MAE": train_mae,
        "Test MAE": test_mae,
        "Train R²": train_r2,
        "Test R²": test_r2
    })

# ------------------------------------------------------------
# STEP 3: Compare all models
# ------------------------------------------------------------
results_df = pd.DataFrame(results)
print(f"\n{'='*60}")
print("MODEL COMPARISON")
print(f"{'='*60}")
print(results_df.to_string(index=False))

# Find best model based on test RMSE
best_model_name = results_df.loc[results_df["Test RMSE"].idxmin(), "Model"]
print(f"\n🏆 Best Model: {best_model_name}")

# ------------------------------------------------------------
# STEP 4: Example predictions with best model
# ------------------------------------------------------------
best_model = models[best_model_name]

# Show some example predictions
example_indices = np.random.choice(len(X_test), size=10, replace=False)
examples = pd.DataFrame({
    "technique_name": usage_wide.iloc[X_test.index[example_indices]]["technique_name"].values,
    "usage_t_minus_2": X_test.iloc[example_indices]["usage_t_minus_2"].values,
    "usage_t_minus_1": X_test.iloc[example_indices]["usage_t_minus_1"].values,
    "actual_current": y_test.iloc[example_indices].values,
    "predicted_current": best_model.predict(X_test.iloc[example_indices])
})

print(f"\n{'='*60}")
print("EXAMPLE PREDICTIONS")
print(f"{'='*60}")
print(examples.to_string(index=False))

Training set size: 401
Test set size: 101

============================================================
Training Linear Regression...
============================================================
Train RMSE: 0.0060 | Test RMSE: 0.0045
Train MAE:  0.0042 | Test MAE:  0.0036
Train R²:   0.9946 | Test R²:   0.9963

============================================================
Training Ridge Regression...
============================================================
Train RMSE: 0.0196 | Test RMSE: 0.0270
Train MAE:  0.0101 | Test MAE:  0.0127
Train R²:   0.9430 | Test R²:   0.8684

============================================================
Training Random Forest...
============================================================
Train RMSE: 0.0049 | Test RMSE: 0.0069
Train MAE:  0.0024 | Test MAE:  0.0042
Train R²:   0.9964 | Test R²:   0.9915

============================================================
Training Gradient Boosting...
============================================================
Train RMSE: 0.0043 | Test RMSE: 0.0067
Train MAE:  0.0026 | Test MAE:  0.0042
Train R²:   0.9973 | Test R²:   0.9918

============================================================
MODEL COMPARISON
============================================================
            Model  Train RMSE  Test RMSE  Train MAE  Test MAE  Train R²  Test R²
Linear Regression    0.006020   0.004506   0.004180  0.003607  0.994618 0.996334
 Ridge Regression    0.019590   0.026994   0.010068  0.012663  0.943002 0.868432
    Random Forest    0.004901   0.006851   0.002446  0.004175  0.996432 0.991525
Gradient Boosting    0.004297   0.006726   0.002622  0.004219  0.997257 0.991832

🏆 Best Model: Linear Regression

============================================================
EXAMPLE PREDICTIONS
============================================================
               technique_name  usage_t_minus_2  usage_t_minus_1  actual_current  predicted_current
                 Malvertising         0.005952         0.006173        0.005952           0.008230
                          VNC         0.023810         0.024691        0.023810           0.026189
                    Web Shell         0.184524         0.179012        0.184524           0.181646
       Mark-of-the-Web Bypass         0.011905         0.018519        0.017857           0.020191
                         Tool         0.440476         0.462963        0.470238           0.464373
      Credentials in Registry         0.011905         0.012346        0.011905           0.014909
            Outlook Home Page         0.005952         0.006173        0.005952           0.008191
                    BITS Jobs         0.035714         0.030864        0.029762           0.033827
System Binary Proxy Execution         0.011905         0.012346        0.011905           0.014909
         File/Path Exclusions         0.005952         0.006173        0.005952           0.008910

In [8]:
# ------------------------------------------------------------
# STEP 1: Train model using t-1 through t-6 to predict current
# ------------------------------------------------------------
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Features: t-1 through t-6
X = usage_wide[["usage_t_minus_1", "usage_t_minus_2", "usage_t_minus_3", 
                "usage_t_minus_4", "usage_t_minus_5", "usage_t_minus_6"]]
y = usage_wide["usage_current"]

# Split and train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print(f"Test RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}")
print(f"Test R²: {r2_score(y_test, y_pred):.4f}")

# ------------------------------------------------------------
# STEP 2: Shift data to predict NEXT period
# ------------------------------------------------------------
# Create a new dataframe where we shift all columns by 1
# What is "current" now becomes "t-1" for prediction purposes
X_future = usage_wide[["usage_current", "usage_t_minus_1", "usage_t_minus_2", 
                       "usage_t_minus_3", "usage_t_minus_4", "usage_t_minus_5"]].copy()

# Rename to match training feature names
X_future.columns = ["usage_t_minus_1", "usage_t_minus_2", "usage_t_minus_3", 
                    "usage_t_minus_4", "usage_t_minus_5", "usage_t_minus_6"]

# ------------------------------------------------------------
# STEP 3: Predict next time period
# ------------------------------------------------------------
predictions_next_period = model.predict(X_future)

# ------------------------------------------------------------
# STEP 4: Create results dataframe
# ------------------------------------------------------------
results = pd.DataFrame({
    "technique_name": usage_wide["technique_name"],
    "usage_current": usage_wide["usage_current"],
    "predicted_next_period": predictions_next_period,
    "predicted_change": predictions_next_period - usage_wide["usage_current"].values
})

# Sort by predicted usage
results = results.sort_values("predicted_next_period", ascending=False)

print("\nTop 20 techniques predicted for next period:")
print(results.head(20))

print("\nTechniques predicted to decline most:")
print(results.sort_values("predicted_change").head(20))

print("\nTechniques predicted to rise most:")
print(results.sort_values("predicted_change", ascending=False).head(20))
results.head(50)

Test RMSE: 0.0045
Test R²: 0.9963

Top 20 techniques predicted for next period:
                                 technique_name  usage_current  \
246                       Ingress Tool Transfer       0.505952
285                              Malicious File       0.500000
350                                  PowerShell       0.494048
457                                        Tool       0.470238
423                    Spearphishing Attachment       0.458333
490                       Windows Command Shell       0.422619
297  Match Legitimate Resource Name or Location       0.351190
483                               Web Protocols       0.333333
441                System Information Discovery       0.327381
370          Registry Run Keys / Startup Folder       0.327381
396                              Scheduled Task       0.321429
209                File and Directory Discovery       0.297619
424                          Spearphishing Link       0.297619
288                              Malicious Link       0.279762
180                      Encrypted/Encoded File       0.220238
207                               File Deletion       0.273810
478                                Visual Basic       0.267857
473                              Valid Accounts       0.261905
195           Exploit Public-Facing Application       0.250000
126                      Data from Local System       0.255952

     predicted_next_period  predicted_change
246               0.500373         -0.005579
285               0.493174         -0.006826
350               0.492778         -0.001270
457               0.468727         -0.001511
423               0.450376         -0.007957
490               0.418249         -0.004370
297               0.387474          0.036283
483               0.330061         -0.003272
441               0.329579          0.002198
370               0.323282         -0.004099
396               0.317813         -0.003616
209               0.296920         -0.000699
424               0.295277         -0.002342
288               0.277169         -0.002593
180               0.272542          0.052304
207               0.269679         -0.004131
478               0.265023         -0.002835
473               0.259782         -0.002122
195               0.257405          0.007405
126               0.253411         -0.002541

Techniques predicted to decline most:
                         technique_name  usage_current  predicted_next_period  \
328     Obfuscated Files or Information       0.107143               0.048581
296   Match Legitimate Name or Location       0.000000              -0.030341
111                    DLL Side-Loading       0.000000              -0.012128
76                   Commonly Used Port       0.000000              -0.011567
400                           Scripting       0.000000              -0.008127
423            Spearphishing Attachment       0.458333               0.450376
285                      Malicious File       0.500000               0.493174
75    Command and Scripting Interpreter       0.101190               0.094681
372              Remote Access Software       0.000000              -0.005720
246               Ingress Tool Transfer       0.505952               0.500373
490               Windows Command Shell       0.422619               0.418249
207                       File Deletion       0.273810               0.269679
370  Registry Run Keys / Startup Folder       0.327381               0.323282
396                      Scheduled Task       0.321429               0.317813
463                Uncommonly Used Port       0.000000              -0.003312
483                       Web Protocols       0.333333               0.330061
110          DLL Search Order Hijacking       0.000000              -0.003095
478                        Visual Basic       0.267857               0.265023
288                      Malicious Link       0.279762               0.277169
126              Data from Local System       0.255952               0.253411

     predicted_change
328         -0.058562
296         -0.030341
111         -0.012128
76          -0.011567
400         -0.008127
423         -0.007957
285         -0.006826
75          -0.006509
372         -0.005720
246         -0.005579
490         -0.004370
207         -0.004131
370         -0.004099
396         -0.003616
463         -0.003312
483         -0.003272
110         -0.003095
478         -0.002835
288         -0.002593
126         -0.002541

Techniques predicted to rise most:
                                 technique_name  usage_current  \
180                      Encrypted/Encoded File       0.220238
297  Match Legitimate Resource Name or Location       0.351190
109                                         DLL       0.190476
373                         Remote Access Tools       0.077381
212                             Financial Theft       0.083333
195           Exploit Public-Facing Application       0.250000
431                    Steal Web Session Cookie       0.047619
152                             Domain Accounts       0.107143
317                             Network Devices       0.023810
380                 Rename Legitimate Utilities       0.035714
194               Exfiltration to Cloud Storage       0.142857
241                               Impersonation       0.047619
83                                  Compression       0.041667
119                   Data Encrypted for Impact       0.101190
461                          Trust Modification       0.011905
376                     Remote Desktop Software       0.053571
242                          Indicator Blocking       0.011905
70                            Code Repositories       0.029762
425                         Spearphishing Voice       0.017857
124                     Data from Cloud Storage       0.029762

     predicted_next_period  predicted_change
180               0.272542          0.052304
297               0.387474          0.036283
109               0.211158          0.020682
373               0.087084          0.009703
212               0.091322          0.007989
195               0.257405          0.007405
431               0.053543          0.005924
152               0.112834          0.005691
317               0.029486          0.005677
380               0.041373          0.005659
194               0.148515          0.005658
241               0.053181          0.005562
83                0.047159          0.005492
119               0.106554          0.005364
461               0.017221          0.005316
376               0.058732          0.005160
242               0.017061          0.005156
70                0.034531          0.004770
425               0.022544          0.004687
124               0.034315          0.004553

,technique_name,usage_current,predicted_next_period,predicted_change
246,Ingress Tool Transfer,0.505952,0.500373,-0.005579
285,Malicious File,0.500000,0.493174,-0.006826
350,PowerShell,0.494048,0.492778,-0.001270
457,Tool,0.470238,0.468727,-0.001511
423,Spearphishing Attachment,0.458333,0.450376,-0.007957
490,Windows Command Shell,0.422619,0.418249,-0.004370
297,Match Legitimate Resource Name or Location,0.351190,0.387474,0.036283
483,Web Protocols,0.333333,0.330061,-0.003272
441,System Information Discovery,0.327381,0.329579,0.002198
370,Registry Run Keys / Startup Folder,0.327381,0.323282,-0.004099
396,Scheduled Task,0.321429,0.317813,-0.003616
209,File and Directory Discovery,0.297619,0.296920,-0.000699
424,Spearphishing Link,0.297619,0.295277,-0.002342
288,Malicious Link,0.279762,0.277169,-0.002593
180,Encrypted/Encoded File,0.220238,0.272542,0.052304
207,File Deletion,0.273810,0.269679,-0.004131
478,Visual Basic,0.267857,0.265023,-0.002835
473,Valid Accounts,0.261905,0.259782,-0.002122
195,Exploit Public-Facing Application,0.250000,0.257405,0.007405
126,Data from Local System,0.255952,0.253411,-0.002541
160,Domains,0.250000,0.252557,0.002557
267,LSASS Memory,0.250000,0.248142,-0.001858
444,System Network Configuration Discovery,0.250000,0.247964,-0.002036
196,Exploitation for Client Execution,0.244048,0.242410,-0.001637
354,Process Discovery,0.238095,0.236002,-0.002093
493,Windows Management Instrumentation,0.232143,0.234964,0.002822
379,Remote System Discovery,0.232143,0.234087,0.001944
135,Deobfuscate/Decode Files or Information,0.226190,0.227288,0.001097
24,Archive via Utility,0.220238,0.224237,0.003999
446,System Owner/User Discovery,0.226190,0.223874,-0.002317
109,DLL,0.190476,0.211158,0.020682
375,Remote Desktop Protocol,0.208333,0.206899,-0.001434
290,Malware,0.202381,0.202454,0.000073
445,System Network Connections Discovery,0.190476,0.194161,0.003685
487,Web Shell,0.184524,0.184657,0.000133
162,Drive-by Compromise,0.184524,0.184366,-0.000158
319,Network Service Discovery,0.184524,0.183313,-0.001210
151,Domain Account,0.178571,0.182522,0.003950
147,Disable or Modify Tools,0.178571,0.178682,0.000110
272,Local Account,0.172619,0.175145,0.002526
301,Modify Registry,0.172619,0.171774,-0.000845
74,Command Obfuscation,0.166667,0.164973,-0.001694
408,Security Software Discovery,0.160714,0.163548,0.002834
274,Local Data Staging,0.160714,0.160407,-0.000307
390,SMB/Windows Admin Shares,0.154762,0.158615,0.003853
496,Windows Service,0.154762,0.157109,0.002347
263,Keylogging,0.154762,0.155594,0.000832
485,Web Services,0.154762,0.155170,0.000408
204,External Remote Services,0.154762,0.154182,-0.000580
386,Rundll32,0.154762,0.153853,-0.000909

In [9]:
# ------------------------------------------------------------
# STEP 2: Iterative prediction function
# ------------------------------------------------------------
def predict_future_periods(usage_wide, model, num_periods=5):
    """
    Predict multiple future periods iteratively.
    
    Parameters:
    - usage_wide: DataFrame with current and historical usage
    - model: Trained model
    - num_periods: Number of future periods to predict
    
    Returns:
    - DataFrame with predictions for each future period
    """
    # Start with current data
    current_data = usage_wide.copy()
    
    # Store predictions
    predictions = {
        "technique_name": current_data["technique_name"],
        "usage_current": current_data["usage_current"]
    }
    
    # Keep track of the latest 6 periods (rolling window)
    latest_usage = current_data[[
        "usage_current", "usage_t_minus_1", "usage_t_minus_2",
        "usage_t_minus_3", "usage_t_minus_4", "usage_t_minus_5"
    ]].values
    
    for period in range(1, num_periods + 1):
        # Prepare features for prediction (rename to match training)
        X_future = pd.DataFrame(
            latest_usage,
            columns=["usage_t_minus_1", "usage_t_minus_2", "usage_t_minus_3",
                    "usage_t_minus_4", "usage_t_minus_5", "usage_t_minus_6"]
        )
        
        # Predict next period
        next_period_pred = model.predict(X_future)
        
        # Store prediction
        predictions[f"predicted_t_plus_{period}"] = next_period_pred
        
        # Shift the window: new prediction becomes most recent
        # Drop oldest (last column), shift everything right, add new prediction at front
        latest_usage = np.column_stack([next_period_pred, latest_usage[:, :-1]])
    
    return pd.DataFrame(predictions)

# ------------------------------------------------------------
# STEP 3: Predict next 5 periods
# ------------------------------------------------------------
future_predictions = predict_future_periods(usage_wide, model, num_periods=5)

# ------------------------------------------------------------
# STEP 4: Add delta columns (change from previous period)
# ------------------------------------------------------------
# Delta from current to t+1
future_predictions["delta_current_to_t_plus_1"] = (
    future_predictions["predicted_t_plus_1"] - future_predictions["usage_current"]
)

# Deltas between consecutive predictions
for i in range(1, 5):
    future_predictions[f"delta_t_plus_{i}_to_t_plus_{i+1}"] = (
        future_predictions[f"predicted_t_plus_{i+1}"] - future_predictions[f"predicted_t_plus_{i}"]
    )

# ------------------------------------------------------------
# STEP 5: Sort by predicted_t_plus_5 (highest to lowest)
# ------------------------------------------------------------
future_predictions = future_predictions.sort_values("predicted_t_plus_5", ascending=False)

print("Predictions for next 5 periods (sorted by t+5):")
print(future_predictions.head(20))

# Optional: Show specific columns for easier reading
display_cols = [
    "technique_name",
    "usage_current",
    "predicted_t_plus_1", "delta_current_to_t_plus_1",
    "predicted_t_plus_2", "delta_t_plus_1_to_t_plus_2",
    "predicted_t_plus_3", "delta_t_plus_2_to_t_plus_3",
    "predicted_t_plus_4", "delta_t_plus_3_to_t_plus_4",
    "predicted_t_plus_5", "delta_t_plus_4_to_t_plus_5"
]

print("\nWith deltas (top 20):")
future_predictions[display_cols].head(20)

Predictions for next 5 periods (sorted by t+5):
                                 technique_name  usage_current  \
297  Match Legitimate Resource Name or Location       0.351190
350                                  PowerShell       0.494048
246                       Ingress Tool Transfer       0.505952
285                              Malicious File       0.500000
457                                        Tool       0.470238
423                    Spearphishing Attachment       0.458333
490                       Windows Command Shell       0.422619
483                               Web Protocols       0.333333
441                System Information Discovery       0.327381
396                              Scheduled Task       0.321429
370          Registry Run Keys / Startup Folder       0.327381
180                      Encrypted/Encoded File       0.220238
209                File and Directory Discovery       0.297619
424                          Spearphishing Link       0.297619
109                                         DLL       0.190476
288                              Malicious Link       0.279762
195           Exploit Public-Facing Application       0.250000
160                                     Domains       0.250000
207                               File Deletion       0.273810
473                              Valid Accounts       0.261905

     predicted_t_plus_1  predicted_t_plus_2  predicted_t_plus_3  \
297            0.387474            0.382337            0.471108
350            0.492778            0.491777            0.490529
246            0.500373            0.496764            0.490852
285            0.493174            0.485644            0.481692
457            0.468727            0.464709            0.467013
423            0.450376            0.446325            0.439165
490            0.418249            0.420070            0.412247
483            0.330061            0.327873            0.329566
441            0.329579            0.332235            0.329561
396            0.317813            0.320007            0.316804
370            0.323282            0.318060            0.315891
180            0.272542            0.287517            0.293625
209            0.296920            0.298585            0.294769
424            0.295277            0.296150            0.295695
109            0.211158            0.209347            0.258563
288            0.277169            0.281630            0.280738
195            0.257405            0.263534            0.268412
160            0.252557            0.254712            0.263133
207            0.269679            0.271100            0.265686
473            0.259782            0.263711            0.260447

     predicted_t_plus_4  predicted_t_plus_5  delta_current_to_t_plus_1  \
297            0.492197            0.505770                   0.036283
350            0.489651            0.486998                  -0.001270
246            0.485412            0.480372                  -0.005579
285            0.475445            0.469966                  -0.006826
457            0.467562            0.465496                  -0.001511
423            0.431138            0.425158                  -0.007957
490            0.409178            0.405672                  -0.004370
483            0.327687            0.325517                  -0.003272
441            0.326375            0.325091                   0.002198
396            0.315216            0.313091                  -0.003616
370            0.312997            0.310430                  -0.004099
180            0.294235            0.306289                   0.052304
209            0.294938            0.294181                  -0.000699
424            0.293768            0.292035                  -0.002342
109            0.271050            0.279699                   0.020682
288            0.278969            0.277317                  -0.002593
195            0.271767            0.274129                   0.007405
160            0.266060            0.267224                   0.002557
207            0.265830            0.264459                  -0.004131
473            0.261400            0.260782                  -0.002122

     delta_t_plus_1_to_t_plus_2  delta_t_plus_2_to_t_plus_3  \
297                   -0.005137                    0.088771
350                   -0.001001                   -0.001248
246                   -0.003610                   -0.005911
285                   -0.007530                   -0.003952
457                   -0.004018                    0.002304
423                   -0.004051                   -0.007160
490                    0.001821                   -0.007823
483                   -0.002188                    0.001693
441                    0.002656                   -0.002674
396                    0.002194                   -0.003203
370                   -0.005222                   -0.002169
180                    0.014975                    0.006107
209                    0.001664                   -0.003815
424                    0.000873                   -0.000455
109                   -0.001811                    0.049216
288                    0.004461                   -0.000892
195                    0.006129                    0.004878
160                    0.002155                    0.008421
207                    0.001421                   -0.005414
473                    0.003928                   -0.003263

     delta_t_plus_3_to_t_plus_4  delta_t_plus_4_to_t_plus_5
297                    0.021089                    0.013573
350                   -0.000878                   -0.002653
246                   -0.005440                   -0.005040
285                   -0.006247                   -0.005479
457                    0.000549                   -0.002066
423                   -0.008026                   -0.005981
490                   -0.003069                   -0.003506
483                   -0.001880                   -0.002170
441                   -0.003187                   -0.001283
396                   -0.001588                   -0.002124
370                   -0.002894                   -0.002567
180                    0.000611                    0.012053
209                    0.000168                   -0.000757
424                   -0.001927                   -0.001733
109                    0.012487                    0.008649
288                   -0.001768                   -0.001652
195                    0.003355                    0.002362
160                    0.002928                    0.001163
207                    0.000144                   -0.001371
473                    0.000952                   -0.000617

With deltas (top 20):

,technique_name,usage_current,predicted_t_plus_1,delta_current_to_t_plus_1,predicted_t_plus_2,delta_t_plus_1_to_t_plus_2,predicted_t_plus_3,delta_t_plus_2_to_t_plus_3,predicted_t_plus_4,delta_t_plus_3_to_t_plus_4,predicted_t_plus_5,delta_t_plus_4_to_t_plus_5
297,Match Legitimate Resource Name or Location,0.351190,0.387474,0.036283,0.382337,-0.005137,0.471108,0.088771,0.492197,0.021089,0.505770,0.013573
350,PowerShell,0.494048,0.492778,-0.001270,0.491777,-0.001001,0.490529,-0.001248,0.489651,-0.000878,0.486998,-0.002653
246,Ingress Tool Transfer,0.505952,0.500373,-0.005579,0.496764,-0.003610,0.490852,-0.005911,0.485412,-0.005440,0.480372,-0.005040
285,Malicious File,0.500000,0.493174,-0.006826,0.485644,-0.007530,0.481692,-0.003952,0.475445,-0.006247,0.469966,-0.005479
457,Tool,0.470238,0.468727,-0.001511,0.464709,-0.004018,0.467013,0.002304,0.467562,0.000549,0.465496,-0.002066
423,Spearphishing Attachment,0.458333,0.450376,-0.007957,0.446325,-0.004051,0.439165,-0.007160,0.431138,-0.008026,0.425158,-0.005981
490,Windows Command Shell,0.422619,0.418249,-0.004370,0.420070,0.001821,0.412247,-0.007823,0.409178,-0.003069,0.405672,-0.003506
483,Web Protocols,0.333333,0.330061,-0.003272,0.327873,-0.002188,0.329566,0.001693,0.327687,-0.001880,0.325517,-0.002170
441,System Information Discovery,0.327381,0.329579,0.002198,0.332235,0.002656,0.329561,-0.002674,0.326375,-0.003187,0.325091,-0.001283
396,Scheduled Task,0.321429,0.317813,-0.003616,0.320007,0.002194,0.316804,-0.003203,0.315216,-0.001588,0.313091,-0.002124
370,Registry Run Keys / Startup Folder,0.327381,0.323282,-0.004099,0.318060,-0.005222,0.315891,-0.002169,0.312997,-0.002894,0.310430,-0.002567
180,Encrypted/Encoded File,0.220238,0.272542,0.052304,0.287517,0.014975,0.293625,0.006107,0.294235,0.000611,0.306289,0.012053
209,File and Directory Discovery,0.297619,0.296920,-0.000699,0.298585,0.001664,0.294769,-0.003815,0.294938,0.000168,0.294181,-0.000757
424,Spearphishing Link,0.297619,0.295277,-0.002342,0.296150,0.000873,0.295695,-0.000455,0.293768,-0.001927,0.292035,-0.001733
109,DLL,0.190476,0.211158,0.020682,0.209347,-0.001811,0.258563,0.049216,0.271050,0.012487,0.279699,0.008649
288,Malicious Link,0.279762,0.277169,-0.002593,0.281630,0.004461,0.280738,-0.000892,0.278969,-0.001768,0.277317,-0.001652
195,Exploit Public-Facing Application,0.250000,0.257405,0.007405,0.263534,0.006129,0.268412,0.004878,0.271767,0.003355,0.274129,0.002362
160,Domains,0.250000,0.252557,0.002557,0.254712,0.002155,0.263133,0.008421,0.266060,0.002928,0.267224,0.001163
207,File Deletion,0.273810,0.269679,-0.004131,0.271100,0.001421,0.265686,-0.005414,0.265830,0.000144,0.264459,-0.001371
473,Valid Accounts,0.261905,0.259782,-0.002122,0.263711,0.003928,0.260447,-0.003263,0.261400,0.000952,0.260782,-0.000617

In [16]:
future_predictions[['technique_name', 'predicted_t_plus_1', 'predicted_t_plus_2', 'predicted_t_plus_3', 'predicted_t_plus_4', 'predicted_t_plus_5']].head(20)

,technique_name,predicted_t_plus_1,predicted_t_plus_2,predicted_t_plus_3,predicted_t_plus_4,predicted_t_plus_5
297,Match Legitimate Resource Name or Location,0.387474,0.382337,0.471108,0.492197,0.505770
350,PowerShell,0.492778,0.491777,0.490529,0.489651,0.486998
246,Ingress Tool Transfer,0.500373,0.496764,0.490852,0.485412,0.480372
285,Malicious File,0.493174,0.485644,0.481692,0.475445,0.469966
457,Tool,0.468727,0.464709,0.467013,0.467562,0.465496
423,Spearphishing Attachment,0.450376,0.446325,0.439165,0.431138,0.425158
490,Windows Command Shell,0.418249,0.420070,0.412247,0.409178,0.405672
483,Web Protocols,0.330061,0.327873,0.329566,0.327687,0.325517
441,System Information Discovery,0.329579,0.332235,0.329561,0.326375,0.325091
396,Scheduled Task,0.317813,0.320007,0.316804,0.315216,0.313091
370,Registry Run Keys / Startup Folder,0.323282,0.318060,0.315891,0.312997,0.310430
180,Encrypted/Encoded File,0.272542,0.287517,0.293625,0.294235,0.306289
209,File and Directory Discovery,0.296920,0.298585,0.294769,0.294938,0.294181
424,Spearphishing Link,0.295277,0.296150,0.295695,0.293768,0.292035
109,DLL,0.211158,0.209347,0.258563,0.271050,0.279699
288,Malicious Link,0.277169,0.281630,0.280738,0.278969,0.277317
195,Exploit Public-Facing Application,0.257405,0.263534,0.268412,0.271767,0.274129
160,Domains,0.252557,0.254712,0.263133,0.266060,0.267224
207,File Deletion,0.269679,0.271100,0.265686,0.265830,0.264459
473,Valid Accounts,0.259782,0.263711,0.260447,0.261400,0.260782

In [10]:
# Create simplified dataframe with just current, t+5, and delta
summary_df = pd.DataFrame({
    "technique_name": future_predictions["technique_name"],
    "usage_current": future_predictions["usage_current"],
    "predicted_t_plus_5": future_predictions["predicted_t_plus_5"],
    "delta_current_to_t_plus_5": future_predictions["predicted_t_plus_5"] - future_predictions["usage_current"]
})

# Sort by predicted_t_plus_5 (highest to lowest)
summary_df = summary_df.sort_values("predicted_t_plus_5", ascending=False)

print("Summary: Current vs Predicted t+5")
summary_df.head(20)

# Or display all rows if you want:
# print(summary_df)

Summary: Current vs Predicted t+5

,technique_name,usage_current,predicted_t_plus_5,delta_current_to_t_plus_5
297,Match Legitimate Resource Name or Location,0.351190,0.505770,0.154579
350,PowerShell,0.494048,0.486998,-0.007050
246,Ingress Tool Transfer,0.505952,0.480372,-0.025580
285,Malicious File,0.500000,0.469966,-0.030034
457,Tool,0.470238,0.465496,-0.004742
423,Spearphishing Attachment,0.458333,0.425158,-0.033176
490,Windows Command Shell,0.422619,0.405672,-0.016947
483,Web Protocols,0.333333,0.325517,-0.007816
441,System Information Discovery,0.327381,0.325091,-0.002290
396,Scheduled Task,0.321429,0.313091,-0.008337
370,Registry Run Keys / Startup Folder,0.327381,0.310430,-0.016951
180,Encrypted/Encoded File,0.220238,0.306289,0.086051
209,File and Directory Discovery,0.297619,0.294181,-0.003438
424,Spearphishing Link,0.297619,0.292035,-0.005584
109,DLL,0.190476,0.279699,0.089223
288,Malicious Link,0.279762,0.277317,-0.002445
195,Exploit Public-Facing Application,0.250000,0.274129,0.024129
160,Domains,0.250000,0.267224,0.017224
207,File Deletion,0.273810,0.264459,-0.009351
473,Valid Accounts,0.261905,0.260782,-0.001122

In [11]:
summary_df.sort_values("delta_current_to_t_plus_5", ascending=False)

,technique_name,usage_current,predicted_t_plus_5,delta_current_to_t_plus_5
297,Match Legitimate Resource Name or Location,0.351190,0.505770,0.154579
109,DLL,0.190476,0.279699,0.089223
180,Encrypted/Encoded File,0.220238,0.306289,0.086051
373,Remote Access Tools,0.077381,0.120612,0.043231
212,Financial Theft,0.083333,0.118449,0.035116
...,...,...,...,...
423,Spearphishing Attachment,0.458333,0.425158,-0.033176
76,Commonly Used Port,0.000000,-0.047973,-0.047973
111,DLL Side-Loading,0.000000,-0.054411,-0.054411
328,Obfuscated Files or Information,0.107143,-0.001668,-0.108810
296,Match Legitimate Name or Location,0.000000,-0.137530,-0.137530

In [12]:
from sklearn.preprocessing import MinMaxScaler

# Create a scaler
scaler = MinMaxScaler()

# Apply min-max scaling to the delta column
summary_df["scaled_score"] = scaler.fit_transform(summary_df[["delta_current_to_t_plus_5"]])

# Sort by delta (highest to lowest)
summary_df = summary_df.sort_values("delta_current_to_t_plus_5", ascending=False)

print("Summary with scaled scores:")
summary_df.head(20)

Summary with scaled scores:

,technique_name,usage_current,predicted_t_plus_5,delta_current_to_t_plus_5,scaled_score
297,Match Legitimate Resource Name or Location,0.351190,0.505770,0.154579,1.000000
109,DLL,0.190476,0.279699,0.089223,0.776260
180,Encrypted/Encoded File,0.220238,0.306289,0.086051,0.765400
373,Remote Access Tools,0.077381,0.120612,0.043231,0.618813
212,Financial Theft,0.083333,0.118449,0.035116,0.591031
376,Remote Desktop Software,0.053571,0.085874,0.032303,0.581401
277,Local Storage Discovery,0.059524,0.091340,0.031816,0.579735
83,Compression,0.041667,0.069959,0.028292,0.567671
476,Virtual Private Server,0.095238,0.122365,0.027127,0.563681
241,Impersonation,0.047619,0.074107,0.026488,0.561495
8,Acquire Infrastructure,0.047619,0.074075,0.026456,0.561384
380,Rename Legitimate Utilities,0.035714,0.062001,0.026287,0.560806
119,Data Encrypted for Impact,0.101190,0.127334,0.026144,0.560317
464,Unix Shell,0.059524,0.083741,0.024217,0.553720
195,Exploit Public-Facing Application,0.250000,0.274129,0.024129,0.553420
258,Junk Code Insertion,0.029762,0.053213,0.023451,0.551098
13,Additional Local or Domain Groups,0.041667,0.064962,0.023296,0.550566
268,Lateral Tool Transfer,0.113095,0.135154,0.022058,0.546331
247,Inhibit System Recovery,0.035714,0.057695,0.021981,0.546066
194,Exfiltration to Cloud Storage,0.142857,0.163839,0.020982,0.542647

In [13]:
# ------------------------------------------------------------
# STEP 1: Merge group techniques with scaled scores
# ------------------------------------------------------------
group_scores = group_techniques_df.merge(
    summary_df[["technique_name", "scaled_score"]],
    on="technique_name",
    how="left"
)

# Fill any missing scores with 0 (in case a technique doesn't have a score)
group_scores["scaled_score"] = group_scores["scaled_score"].fillna(0)

# ------------------------------------------------------------
# STEP 2: Sum scaled scores per group
# ------------------------------------------------------------
group_weighted_scores = (
    group_scores.groupby("group_name")["scaled_score"]
    .sum()
    .reset_index(name="total_weighted_score")
)

# Sort by total weighted score (highest to lowest)
group_weighted_scores = group_weighted_scores.sort_values("total_weighted_score", ascending=False)

print("Group Weighted Scores (sorted by total score):")
print(group_weighted_scores.head(20))

# Optional: Add count of techniques per group for additional context
technique_counts = (
    group_techniques_df.groupby("group_name")
    .size()
    .reset_index(name="num_techniques")
)

group_weighted_scores = group_weighted_scores.merge(technique_counts, on="group_name")

print("\nWith technique counts:")
group_weighted_scores.head(20)

Group Weighted Scores (sorted by total score):
           group_name  total_weighted_score
80            Kimsuky             54.288133
82      Lazarus Group             46.613825
7               APT28             45.391824
100     Mustang Panda             42.154619
156      Volt Typhoon             40.915974
16              APT41             40.724450
89        Magic Hound             39.560615
121     Sandworm Team             39.149036
11              APT32             38.917869
104            OilRig             37.577241
69    Gamaredon Group             34.286484
152             Turla             33.940033
61               FIN7             33.286046
8               APT29             32.986449
123  Scattered Spider             32.658376
164     Wizard Spider             31.059599
36            Chimera             29.703667
143           TeamTNT             28.610885
99         MuddyWater             28.589048
91       Medusa Group             28.504248

With technique counts:

          group_name  total_weighted_score  num_techniques
0            Kimsuky             54.288133             109
1      Lazarus Group             46.613825              93
2              APT28             45.391824              91
3      Mustang Panda             42.154619              85
4       Volt Typhoon             40.915974              81
5              APT41             40.724450              82
6        Magic Hound             39.560615              79
7      Sandworm Team             39.149036              79
8              APT32             38.917869              78
9             OilRig             37.577241              76
10   Gamaredon Group             34.286484              70
11             Turla             33.940033              68
12              FIN7             33.286046              67
13             APT29             32.986449              66
14  Scattered Spider             32.658376              64
15     Wizard Spider             31.059599              64
16           Chimera             29.703667              59
17           TeamTNT             28.610885              56
18        MuddyWater             28.589048              58
19      Medusa Group             28.504248              57

In [14]:
# Create a scaler
scaler = MinMaxScaler()

# Apply min-max scaling to the total weighted score
group_weighted_scores["scaled_group_score"] = scaler.fit_transform(
    group_weighted_scores[["total_weighted_score"]]
)

# Sort by scaled score (highest to lowest)
group_weighted_scores = group_weighted_scores.sort_values("scaled_group_score", ascending=False)

print("Group Weighted Scores with Min-Max Scaling:")
group_weighted_scores.head(20)

Group Weighted Scores with Min-Max Scaling:

          group_name  total_weighted_score  num_techniques  scaled_group_score
0            Kimsuky             54.288133             109            1.000000
1      Lazarus Group             46.613825              93            0.858381
2              APT28             45.391824              91            0.835831
3      Mustang Panda             42.154619              85            0.776092
4       Volt Typhoon             40.915974              81            0.753235
5              APT41             40.724450              82            0.749701
6        Magic Hound             39.560615              79            0.728223
7      Sandworm Team             39.149036              79            0.720628
8              APT32             38.917869              78            0.716362
9             OilRig             37.577241              76            0.691623
10   Gamaredon Group             34.286484              70            0.630897
11             Turla             33.940033              68            0.624503
12              FIN7             33.286046              67            0.612435
13             APT29             32.986449              66            0.606906
14  Scattered Spider             32.658376              64            0.600852
15     Wizard Spider             31.059599              64            0.571349
16           Chimera             29.703667              59            0.546327
17           TeamTNT             28.610885              56            0.526161
18        MuddyWater             28.589048              58            0.525758
19      Medusa Group             28.504248              57            0.524193

CSV exporting

In [15]:
# csv_df = group_weighted_scores[['group_name', 'scaled_group_score']]
# csv_df.rename(columns={'scaled_group_score': 'score'}, inplace=True)
# csv_df.to_csv("../analysis_data/technique_predictions.csv", index=False)